## DEFINE WORKFLOW NAME
name: Deploy to GitHub Pages

## DEFINE WHEN TO RUN
## PUSH HAS BEEN DISABLED ON MAIN BRANCH, MEANING THAT THIS WILL ONLY RUN AFTER A PR
on:
  push:
    branches:
      - main
  pull_request:
  
## DEFINE WORKFLOW
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      ## SETUP HUGO
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      ## BUILD HUGO WEBSITE
      - name: Build
        working-directory: ./blog
        run: hugo --minify

      ## DEPLOY TO GITHUB PAGES
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          cname: dodbrit.io