## DEFINE WORKFLOW NAME
name: Deploy to GitHub Pages

## DEFINE WHEN TO RUN
## PUSH HAS BEEN DISABLED ON MAIN BRANCH, MEANING THAT THIS WILL ONLY RUN AFTER A PR
on:
  push:
    branches:
      - main

## DEFINE WORKFLOW
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd app
          npm install 
          npm run build
      
      ## DEPLOY BLOG TO PAGES
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com