## DEFINE WORKFLOW NAME
name: Deploy to GitHub Pages

## DEFINE WHEN TO RUN
## PUSH HAS BEEN DISABLED ON MAIN BRANCH, MEANING THAT THIS WILL ONLY RUN AFTER A PR
on:
  push:
    branches:
      - main

## DEFINE WORKFLOW
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd website
          npm install 
          npm run build
      
      ## DEPLOY BLOG TO PAGES
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}